name: CommunityVault
main: org.niels.communityVault.CommunityVault
version: "1.2"
author: Niels
api-version: '1.21'
commands:
  cvault:
    usage: /cvault
    description: Opens the CommunityVault
  buywc:
    usage: /buywc
    description: Buy a withdrawal chest (costs diamonds)
  buydc:
    usage: /buydc
    description: Buy a deposit chest (costs diamonds)
  searchvault:
    usage: /searchvault
    description: Search the CommunityVault.
  sv:
    usage: /sv
    description: Search the CommunityVault (short).
  cvaultcompact:
    usage: /cvaultcompact
    description: Compact and save the CommunityVault (admin).
  cvaultstatus:
    usage: /cvaultstatus
    description: Show CommunityVault health info (admin).
